version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "cron"
          cronjob: "0 8 21 * *"
      labels:
          - "dependabot"
      commit-message:
          prefix: "chore"
      open-pull-requests-limit: 5
      cooldown:
          default-days: 7
          include:
              - "*"
      groups:
          actions-all:
              patterns:
                  - "*"
              update-types:
                  - "major"
                  - "minor"
                  - "patch"
